# Source this file in your shell for this project session.
export MEMSEARCH_PROVIDER="ollama"
export MEMSEARCH_MODEL="nomic-embed-text"
export PM="/Users/pranay/Projects/projects-memory"
export PROJECT_REL="Data_Science/computer_vision/proj6/signature-extractor-app"
export AGENT_DOCTRINE_SOURCE="/Users/pranay/Downloads/OPERATING_DOCTRINE.md"
export AGENT_DOCTRINE_VERSION="6.0"
export AGENT_DOCTRINE_SHA256="a49b686d381b2a9d83c57028138f59821686627b319085d40f54030bfca4ab45"
export PROJECT_DOCTRINE_FILE="/Users/pranay/Projects/Data_Science/computer_vision/proj6/signature-extractor-app/OPERATING_DOCTRINE.md"
export AGENT_SESSION_CONTEXT="/Users/pranay/Projects/Data_Science/computer_vision/proj6/signature-extractor-app/docs/context/agent-start/SESSION_CONTEXT.md"
export AGENT_KICKOFF_PROMPT="/Users/pranay/Projects/Data_Science/computer_vision/proj6/signature-extractor-app/docs/context/agent-start/AGENT_KICKOFF_PROMPT.txt"
