# Source this file in your shell for this project session.
export MEMSEARCH_PROVIDER="ollama"
export MEMSEARCH_MODEL="nomic-embed-text"
export PM="/Users/pranay/Projects/projects-memory"
export PROJECT_REL="Data_Science/computer_vision/proj6/signature-extractor-app"
export AGENT_DOCTRINE_SOURCE="/Users/pranay/Projects/Data_Science/computer_vision/proj6/signature-extractor-app/motto_v5.md"
export AGENT_DOCTRINE_VERSION="5"
export AGENT_DOCTRINE_SHA256="f1ade186d46bf2e20e9eebd56ceca3a733711671471198284828482659524840"
export PROJECT_DOCTRINE_FILE="/Users/pranay/Projects/Data_Science/computer_vision/proj6/signature-extractor-app/motto_v5.md"
export AGENT_SESSION_CONTEXT="/Users/pranay/Projects/Data_Science/computer_vision/proj6/signature-extractor-app/docs/context/agent-start/SESSION_CONTEXT.md"
export AGENT_KICKOFF_PROMPT="/Users/pranay/Projects/Data_Science/computer_vision/proj6/signature-extractor-app/docs/context/agent-start/AGENT_KICKOFF_PROMPT.txt"
